name: 20.04 | 22.04 | win2019 | win2022

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2019, windows-2022]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config=${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          python3 ${{github.workspace}}/build/tests/run_standard_tests.py
